name: report

on:
  workflow_run:
    workflows: [ build ]
    types: [ completed ]

permissions:
  checks: write

run-name: ${{ github.event.workflow_run.id }} (Process Test Results)

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Download Test Results
        uses: dawidd6/action-download-artifact@v3
        with:
          name: junit-test-results
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Results
        uses: mikepenz/action-junit-report@v4
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          report_paths: '**/build/test-results/test/TEST-*.xml'
          include_passed: true
